<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AForge.Video, Version=2.2.5.0, Culture=neutral, PublicKeyToken=cbfb6e07d173c401">
      <HintPath>..\musor\Libraries\AForge.Video.dll</HintPath>
    </Reference>
    <Reference Include="AForge.Video.FFMPEG, Version=2.2.5.0, Culture=neutral, PublicKeyToken=03563089b1be05dd">
      <HintPath>..\musor\Libraries\AForge.Video.FFMPEG.dll</HintPath>
    </Reference>
    <Reference Include="log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a">
      <HintPath>..\musor\Libraries\log4net\log4net.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Practices.Unity, Version=2.1.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
      <HintPath>..\musor\Libraries\Unity\Microsoft.Practices.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Practices.Unity.Configuration, Version=2.1.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
      <HintPath>..\musor\Libraries\Unity\Microsoft.Practices.Unity.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="WeifenLuo.WinFormsUI.Docking, Version=2.9.0.0, Culture=neutral, PublicKeyToken=5cded1a1a0a7b481">
      <HintPath>..\musor\Libraries\WeifenLuo.WinFormsUI.Docking.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ICSharpCode.SharpZipLib.Patched" Version="1.2.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ZXMAK2.Hardware\GeneralSoundDevice.cs" />
    <Compile Remove="ZXMAK2.DirectX\DirectSound\Blob.cs" />
    <Compile Remove="ZXMAK2.Host.WinForms\Mdx\Renderers.mdx\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="ZXMAK2.Host.WinForms\Mdx\Renderers.mdx\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="ZXMAK2.Host.WinForms\Mdx\Renderers.mdx\**" />
  </ItemGroup>
</Project>
