<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace />
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Practices.Unity, Version=2.1.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
      <HintPath>..\musor\Libraries\Unity\Microsoft.Practices.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Practices.Unity.Configuration, Version=2.1.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
      <HintPath>..\musor\Libraries\Unity\Microsoft.Practices.Unity.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="ZXMAK2.DirectX">
      <HintPath>..\musor\_bindebug\ZXMAK2.DirectX.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ICSharpCode.SharpZipLib.Patched" Version="1.2.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ZXMAK2.Hardware\GeneralSoundDevice.cs" />
    <Compile Remove="ZXMAK2.DirectX\DirectSound\Blob.cs" />
    <Compile Remove="ZXMAK2.Host.WinForms\Mdx\Renderers.mdx\**" />
    <None Remove="ZXMAK2.DirectX\Native\NativeHelper.il" />
    <Compile Include="ZXMAK2.DirectX\Native\NativeHelper.il" />
    <None Remove="ZXMAK2.DirectX\Direct3D\Direct3DDevice9.il" />
    <Compile Include="ZXMAK2.DirectX\Direct3D\Direct3DDevice9.il" />
    <Compile Remove="ZXMAK2.DirectX\**" />
    <None Remove="ZXMAK2.DirectX\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ZXMAK2.Resources\Pictures\KeyboardHelp.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Pictures\ZXLogo.gif" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\DebuggerBreak.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\DebuggerClose.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\DebuggerContinue.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\DebuggerShowBreakpoints.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\DebuggerShowNext.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\DebuggerStepInto.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\DebuggerStepOut.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\DebuggerStepOver.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuColdReset_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuFileOpen_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuFileSave_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuFullScreen_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuMaxSpeed_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuPause_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuQuickLoad_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuResume_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuSettings_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuWarmReset_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\EmuWindowed_32x32.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\HardwareTapeAutoplay.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\HardwareTapeNext.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\HardwareTapePause.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\HardwareTapePlay.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\HardwareTapePrev.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\HardwareTapeRecord.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\HardwareTapeRewind.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\HardwareTapeTraps.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\IconApp.ico" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\IconDebugger.ico" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\OsdFddRd.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\OsdFddWr.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\OsdHddRd.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\OsdPause.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\OsdTapeRd.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\Stop_real_16x16.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Icons\Wizard.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\AY8910.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\BEEPER.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\DEBUG.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\DISPLAY.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\FDD.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\KBD.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\MOUS.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\PCB.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\RAM.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\TAPE.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\DeviceIcons\ULA.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\Asaaam.ico" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\Asm.ico" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\AsmSettings.ico" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\compileToolStrip.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\openFileStripButton.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\saveFileStripButton.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\settingsToolStrip.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\toolCodeLibrary.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\toolStripButtonReloadFile.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\toolStripColors.png" />
    <EmbeddedResource Include="ZXMAK2.Resources\Adlers\toolStripNewSource.png" />
  </ItemGroup>
</Project>
